# -*- coding: utf-8 -*-
"""基礎設施共用常數(batch/motion/reader/capture 預設值與舊資源根目錄)。"""
from pathlib import Path


SUPPORTED_BATCH_SIZES = (1, 2, 4, 8)
DEFAULT_FG_MASK_SCALE = 0.5
DEFAULT_MOTION_DIFF_THRESHOLD = 10
DEFAULT_MOTION_DILATE_ITERATIONS = 2
DEFAULT_MOTION_BLUR_KERNEL = 0
DEFAULT_MOTION_OPEN_KERNEL = 3
DEFAULT_MOTION_OPEN_ITERATIONS = 0
DEFAULT_MOTION_CLOSE_KERNEL = 0
DEFAULT_MOTION_CLOSE_ITERATIONS = 0
DEFAULT_MOTION_MIN_COMPONENT_AREA = 4
DEFAULT_MOTION_MIN_LARGEST_COMPONENT_RATIO = 0.25
DEFAULT_READER_QUEUE_SIZE = 32
DEFAULT_CAPTURE_BUFFER_SIZE = 8
LEGACY_RESOURCE_ROOT = Path("/mnt/8tb_hdd/under115a")
